### ISSUE TITLE
Guide: How to use it with Laravel 5

### ISSUE THREAD

**Issue by chriskonnertz** [thujohn/rss-l4#21]
Hello,

to use rss-l4 in Laravel 5, follow the installation steps explained in the Readme file ( https://github.com/thujohn/rss-l4/blob/master/README.md ), but skip the step that adds the service provider.

The service provider is incompatible with Laravel 5.

Therefore, open `app/Providers/AppServiceProvider.php`. Find the `register` method. Add these lines:

``` php
    $this->app['rss'] = $this->app->share(function($app)
    {
        return new \Thujohn\Rss\Rss;
    });
```

That's it.

**Comment by Stichoza** [comment]
:+1:

**Comment by chriskonnertz** [comment]
Unfortunately the creator of this repository does not seem to maintain it any longer.
